repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-added-large-files
        args: [--maxkb=1000]

  # TypeScript/JavaScript specific checks
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.17.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        exclude: ^example/
        types: [file]
        additional_dependencies:
          - '@eslint/js@^9.33.0'
          - 'eslint@^9.33.0'
          - 'eslint-plugin-react-hooks@^5.2.0'
          - 'eslint-plugin-react-refresh@^0.4.20'
          - 'typescript-eslint@^8.39.1'
          - 'globals@^16.3.0'
        args: [--fix]

  # Prettier for code formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|scss|md|yaml|yml)$
        additional_dependencies:
          - prettier@^3.0.0
        args: [--write]

  # TypeScript type checking
  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript type check
        entry: npm run type-check
        language: system
        files: \.(ts|tsx)$
        pass_filenames: false

  # Security checks for npm packages
  - repo: local
    hooks:
      - id: npm-audit
        name: npm audit
        entry: npm audit --audit-level=moderate
        language: system
        pass_filenames: false
        files: package-lock.json
